export declare const User: unique symbol;
export declare const Product: unique symbol;
export declare const Category: unique symbol;
export declare const Order: unique symbol;
export declare const Customer: unique symbol;
export declare const Post: unique symbol;
export declare const Comment: unique symbol;
export declare const File: unique symbol;
export declare const Tag: unique symbol;
export declare const Role: unique symbol;
export declare const Permission: unique symbol;
export declare const Group: unique symbol;
export declare const Setting: unique symbol;
export declare const Notification: unique symbol;
export declare const Message: unique symbol;
export declare const Event: unique symbol;
export declare const Task: unique symbol;
export declare const Project: unique symbol;
export declare const Team: unique symbol;
export declare const Payment: unique symbol;
export declare const Subscription: unique symbol;
export declare const Invoice: unique symbol;
export declare const Address: unique symbol;
export declare const Review: unique symbol;
export declare const Feedback: unique symbol;
export declare const Metric: unique symbol;
export declare const Log: unique symbol;
export declare const Report: unique symbol;
export declare const Dashboard: unique symbol;
export declare const Profile: unique symbol;
export declare const Account: unique symbol;
export declare const resourceSymbols: {
    User: symbol;
    Product: symbol;
    Category: symbol;
    Order: symbol;
    Customer: symbol;
    Post: symbol;
    Comment: symbol;
    File: symbol;
    Tag: symbol;
    Role: symbol;
    Permission: symbol;
    Group: symbol;
    Setting: symbol;
    Notification: symbol;
    Message: symbol;
    Event: symbol;
    Task: symbol;
    Project: symbol;
    Team: symbol;
    Payment: symbol;
    Subscription: symbol;
    Invoice: symbol;
    Address: symbol;
    Review: symbol;
    Feedback: symbol;
    Metric: symbol;
    Log: symbol;
    Report: symbol;
    Dashboard: symbol;
    Profile: symbol;
    Account: symbol;
};
export declare function createResource(name: string): symbol;
